### ISSUE TITLE
aiokubernetes doesn`t work with insecure-skip-tls-verify option

### ISSUE THREAD

**Issue by darelvc** [olitheolix/aiokubernetes#18]
Hello,

When I used insecure-skip-tls-verify option in kubeconfig file I got an error

```
Traceback (most recent call last):
  File "/Users/obloshenkin/my_project/learn_angular/api_health_chek/examples/async_kubectl.py", line 42, in <module>
    loop.run_until_complete(main())
  File "/Users/obloshenkin/.pyenv/versions/3.6.5/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/Users/obloshenkin/my_project/learn_angular/api_health_chek/examples/async_kubectl.py", line 9, in main
    context='preprod'
  File "/Users/obloshenkin/.pyenv/versions/3.6.5/lib/python3.6/site-packages/aiokubernetes/config/kube_config.py", line 477, in new_client_from_config
    return ApiClient(configuration=client_config)
  File "/Users/obloshenkin/.pyenv/versions/3.6.5/lib/python3.6/site-packages/aiokubernetes/api_client.py", line 88, in __init__
    verify_ssl=configuration.verify_ssl
  File "/Users/obloshenkin/.pyenv/versions/3.6.5/lib/python3.6/site-packages/aiohttp/connector.py", line 643, in __init__
    fingerprint)
  File "/Users/obloshenkin/.pyenv/versions/3.6.5/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 118, in _merge_ssl_params
    raise ValueError("verify_ssl, ssl_context, fingerprint and ssl "
ValueError: verify_ssl, ssl_context, fingerprint and ssl parameters are mutually exclusive
```
My kubeconfig:

```
apiVersion: v1
kind: Config
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://hostname-address:6443
  name: preprod
```

This error raised for me because in the module __init__() contains these changes:

```
ssl_context = ssl.create_default_context(cafile=ca_certs)
        if configuration.cert_file:
            ssl_context.load_cert_chain(
                configuration.cert_file, keyfile=configuration.key_file
            )

        connector = aiohttp.TCPConnector(
            limit=4,
            ssl_context=ssl_context,
            verify_ssl=configuration.verify_ssl
        )

```

Please help me.

Thank you.

**Comment by olitheolix** [comment]
I am still refactoring the code base so you can bring (and configure) your own client.

In the meantime, you can build your own API Client and use that. The example below shows how to do just that. The `ApiClientSkipTLS` class is a verbatim copy of the original `APIClient` constructor but I commented out the `verify_ssl=configuration.verify_ssl` line that, I believe, is the source of your troubles.

```
import asyncio
import aiohttp
import certifi
import ssl

import aiokubernetes as k8s


class ApiClientSkipTLS(k8s.api_client.ApiClient):
    def __init__(self, configuration, header_name=None, header_value=None, cookie=None):

        self.default_headers = {}
        if header_name is not None:
            self.default_headers[header_name] = header_value
        self.cookie = cookie

        # Set default User-Agent.
        self.user_agent = 'Swagger-Codegen/1.0/python'

        self.configuration = configuration

        # ca_certs
        if configuration.ssl_ca_cert:
            ca_certs = configuration.ssl_ca_cert
        else:
            # if not set certificate file, use Mozilla's root certificates.
            ca_certs = certifi.where()

        ssl_context = ssl.create_default_context(cafile=ca_certs)
        if configuration.cert_file:
            ssl_context.load_cert_chain(
                configuration.cert_file, keyfile=configuration.key_file
            )

        connector = aiohttp.TCPConnector(
            limit=4,
            ssl_context=ssl_context,
            # verify_ssl=configuration.verify_ssl
        )

        # https pool manager
        self.session = aiohttp.ClientSession(connector=connector)


async def main():
    # Load ~/.kube/config or whatever KUBECONFIG points to.
    client_config = k8s.Configuration()
    k8s.config.kube_config.load_kube_config(
        config_file=None, context=None,
        client_configuration=client_config,
        persist_config=True)

    # Instantiate customised client.
    api_client = ApiClientSkipTLS(configuration=client_config)

    # Ask for all name-spaces.
    ret = await k8s.api.CoreV1Api(api_client).list_namespace()

    # Ensure the API call to Kubernetes succeeded.
    assert ret.http.status == 200

    # Print the pod names.
    for i in ret.obj.items:
        print(f"{i.metadata.namespace} {i.metadata.name}")

    # Close all pending connections.
    await api_client.close()


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
    loop.close()
```

Does this help?

**Comment by darelvc** [comment]
You are amazing!!!

I change connector = aiohttp.TCPConnector( ... ) to 

```
# https pool manager
        connector = aiohttp.TCPConnector(
            verify_ssl=False,
            limit=4
        )

        self.session = aiohttp.ClientSession(
            connector=connector,
            conn_timeout=35.0,
            read_timeout=30.0
        )
```

And it works for me as well!!!

Awesome!
Thank you.

**Comment by olitheolix** [comment]
Happy to hear it works for you now.
